# Generated by Django 4.1.3 on 2022-11-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_usercustom_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='state',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='fulladdress',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
