# Generated by Django 4.1.3 on 2022-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_remove_usercustom_state_usercustom_fulladdress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='user',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='fulladdress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
