# Generated by Django 4.1.3 on 2022-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_usercustom_user_usercustom_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
