# Generated by Django 4.1.3 on 2022-11-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_usercustom_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
