# Generated by Django 4.1.3 on 2022-11-21 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0014_usercustom_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='password',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
