# Generated by Django 4.1.3 on 2022-11-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_usercustom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='code_post',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
