# Generated by Django 4.1.3 on 2022-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_product_price_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nameFa',
        ),
        migrations.AddField(
            model_name='category',
            name='nameEn',
            field=models.CharField(default=None, max_length=255, verbose_name='اسم انگلیسی'),
        ),
    ]
