# Generated by Django 4.1.3 on 2022-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_rename_name_category_namefa_category_nameen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nameEn',
            field=models.CharField(max_length=255, verbose_name='اسم انگلیسی'),
        ),
    ]
