# Generated by Django 4.1.3 on 2022-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_category_options_alter_category_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Tpost',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='brandmobile',
            name='Tpost',
            field=models.IntegerField(default=0, verbose_name='تعداد پست'),
        ),
        migrations.AddField(
            model_name='brandmobile',
            name='image',
            field=models.ImageField(default=None, upload_to='category', verbose_name='عکس '),
            preserve_default=False,
        ),
    ]
