# Generated by Django 4.1.3 on 2022-11-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_brandmobile_nameen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmobile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم '),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brandmobile'),
        ),
    ]
