# Generated by Django 4.1.3 on 2022-11-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_product_mojood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jamsabad',
            options={},
        ),
    ]
