# Generated by Django 4.1.3 on 2022-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_colors_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='color',
            field=models.CharField(default='black', max_length=255),
        ),
    ]
