# Generated by Django 4.1.3 on 2022-11-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_sabad_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='image_u',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userphone',
            name='name',
        ),
        migrations.DeleteModel(
            name='Image_trend_2',
        ),
        migrations.DeleteModel(
            name='image_u',
        ),
        migrations.DeleteModel(
            name='Userphone',
        ),
    ]
